name 'maestrodev-maestro_nodes'
version '1.2.0'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-maestro_nodes'
source 'http://github.com/maestrodev/puppet-maestro_nodes'
summary 'Maestro related services'
description 'Maestro related services installation and configuration: jenkins, sonar, archiva,...'

dependency 'maestrodev/ant', '>=1.0.3'
dependency 'maestrodev/archiva', '1.x'
dependency 'maestrodev/git', '>=1.0.0'
dependency 'maestrodev/svn'
dependency 'maestrodev/jenkins'
dependency 'maestrodev/maestro', '>=1.0.0'
dependency 'maestrodev/maven', '>=0.0.2'
dependency 'maestrodev/sonar', '1.x'
dependency 'maestrodev/rvm'
dependency 'maestrodev/ssh_keygen', '1.x'
dependency 'puppetlabs/mongodb'
dependency 'maestrodev/activemq'

