forge 'http://forge.puppetlabs.com'

mod 'maestrodev/ant', '>=1.0.3'
mod 'maestrodev/archiva', '~>1.0'
mod 'maestrodev/git', '>=1.0.0'
mod 'maestrodev/svn'
mod 'maestrodev/jenkins'
mod 'maestrodev/maestro', '>=1.0.0'
mod 'maestrodev/maven', '>=0.0.2'
mod 'maestrodev/sonar', '~>1.0'
mod 'maestrodev/rvm'
mod 'maestrodev/ssh_keygen', '~>1.0'
